=== creads/partners-doc/src/references/schemas/app.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "App",
  "type": "object",
  "properties": {
    "gid": {
      "type": "string",
      "readOnly": true
    },
    "href": {
      "type": "string",
      "readOnly": true
    },
    "created_at": {
      "type": "string",
      "format": "date-time",
      "readOnly": true
    },
    "modified_at": {
      "type": "string",
      "format": "date-time",
      "readOnly": true
    },
    "name": {
      "type": "string",
      "maxLength": 80,
      "required": true
    },
    "app_id": {
      "type": "string",
      "readOnly": true
    },
    "app_secret": {
      "type": "string",
      "readOnly": true
    },
    "callback_url": {
      "type": "string",
      "format": "uri",
      "required": true
    },
    "allowed_grant_types": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "authorization_code",
          "password",
          "refresh_token",
          "client_credentials",
          "jwt_token"
        ]
      },
      "required": true
    },
    "owner": {
      "$ref": "user.reference.json",
      "required": true
    }
  },
  "additionalProperties": false
}

=== creads/partners-doc/src/references/samples/app.json
{
    "gid": "559bee7c1e8d9",
    "created_at": "2015-06-11T11:51:16+0200",
    "app_id": "1_2kdg0sbb9r8kgg04g4gwo4og888kwg40k8ock8co8kscsgkwkg",
    "app_secret": "hmcp8emwobsoosgss4g0okg88k0wkcwcg4ko8gg48skkosgks",
    "callback_url": "http://localhost:3000",
    "allowed_grant_types": ["password"],
    "name": "App",
    "href": "/apps/559bee7c1e8d9",
    "owner": {
        "gid": "559bee86b11b6",
        "href": "/users/559bee86b11b6"
    }
}
