=== creads/partners-doc/src/references/schemas/comment.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "type": "object",
  "properties": {
    "gid": {
      "type": "string",
      "readOnly": true
    },
    "created_at": {
      "type": "string",
      "format": "date-time"
    },
    "modified_at": {
      "type": "string",
      "format": "date-time",
      "readOnly": true
    },
    "message": {
      "type": "string",
      "minLength": 0,
      "maxLength": 8000,
      "required": true
    },
    "uri": {
      "type": "string",
      "minLength": 0,
      "maxLength": 255,
      "required": true
    },
    "author": {
        "oneOf": [
            {"type": "null"},
            {"$ref": "user.public.json"}
        ],
        "required": false
    },
    "worker": {
        "oneOf": [
            {"type": "null"},
            {"$ref": "worker.reference.json"}
        ],
        "required": false
    },
    "mine": {
      "type": "boolean",
      "readOnly": true
    },
    "nickname": {
      "type": "string",
      "readOnly": true
    },
    "avatar": {
      "oneOf": [
          {"type": "null"},
          {"$ref": "image.json"}
      ],
      "required": false,
      "readOnly": true
    }
  },
  "definitions": {
  }
}

=== creads/partners-doc/src/references/samples/comment.json
{
  "gid": "559bef42c09b7",
  "created_at": "2014-09-08T22:47:31-08:00",
  "modified_at": "2014-09-08T22:47:31-08:00",
  "author": {
    "gid": "559bef4a9b600"
  },
  "worker": null,
  "message": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras scelerisque viverra sodales. Vestibulum quis fringilla nisi. Donec congue neque ac consequat vestibulum. Praesent sed urna maximus ante ornare vestibulum. In in vulputate sapien. Ut elementum bibendum mi sit amet congue. Aliquam suscipit turpis vitae dapibus efficitur. Nullam quis lacinia ligula. Nam at lectus sem.",
  "mine": true,
  "uri": "/works/559bef4a9b600",
  "nickname": "Bernard L."
}
